@startuml
title AutoRunAll时序图
autonumber
hide footbox
actor 用户 as U
participant MainActivity as M
U ->>M: 点击自\n动运行
activate M
M -> M: onOptionsItemSelected
activate M
M ->> M: handleRunStopAll()
activate M
M ->M: updateRunAllUI(true)
activate M
deactivate M
M->M:runAll()
activate M
participant MainPresenter as mp
== 当 TestCast.getAuto()=true时转至下个TestCase ==
M -> mp:runAll()
activate M
activate mp
participant CaseManager as cm
mp -> cm: runCase()
activate cm
participant TestCase as tc
cm -> tc:runCase()
activate tc
participant CaseServiceManager as csm
cm->csm:runCase()
deactivate tc
activate csm
cm <--csm:runService\n return int
deactivate M
deactivate csm
deactivate mp
deactivate cm

autonumber 6
== 当 TestCast.getAuto()=false时启动测试项的activity ==
participant BaseActivity as ba
note over ba: 每一个继承BaseActivity的子类是测试项
M -> ba :startCaseActivity\nForResult()
activate M
activate ba
participant BasePresenter as bp
ba->bp:onResume()
activate bp
participant CaseManager as cm
bp->cm:runCase()
activate cm
participant CaseServiceManager as csm
cm->csm:runCase()
activate csm
csm->csm:runService()
activate csm
csm->csm:goRun()
activate csm
participant BaseService.ServiceHandler as bsh
csm->>bsh:sendMsg()
activate csm
activate bsh
participant BaseService as bs
bsh->bs:handleMsg()
activate bs
participant SystemInfoService as sis
bs->sis:run()
activate sis
sis->bs:run()
activate bs
bs->ba:updateView()
activate ba
deactivate ba
deactivate ba
== 点击"PASS"或"FAIL"返回结果 ==
ba->>ba:onClick()
activate ba
ba->ba:feedbackResult()
activate ba
ba-->>M:setResult()
activate M
deactivate M
deactivate M
deactivate M
deactivate M
deactivate M
deactivate M
M->M:onActivityResult()
activate M
@enduml